# Generated by Django 5.1.1 on 2024-10-04 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_date_published_blogpost_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
