# Generated by Django 5.1.1 on 2024-10-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_blogpost_author_alter_blogpost_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='landmarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='machinery_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='region',
            field=models.CharField(default='Unknown Region', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='scale',
            field=models.CharField(default='Unknown Region', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='town',
            field=models.CharField(default='Unknown Town', max_length=100),
            preserve_default=False,
        ),
    ]
