# Generated by Django 5.1.1 on 2024-10-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_additional_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='environmental_impact',
            field=models.CharField(default=['Water pollution'], max_length=255),
            preserve_default=False,
        ),
    ]
