# Generated by Django 5.1.1 on 2024-10-17 22:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_report_environmental_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='references',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
