# Generated by Django 5.1.1 on 2024-10-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_blogpost_content_alter_blogpost_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
